epochs: 200
batch_size: 512
learning_rate: 5e-4
early_stopping: 100

# optimizer
optimizer: "Adam"
optimizer_b1: 0.9
optimizer_b2: 0.98
optimizer_e: 10e-9

# regularization
label_smoothing_value: 0.1

# activation
activate: "Relu"

# weight initialization of choice [he, xavier] and Weight distribution of choice [uniform, normal]
weight_init: "he"
weight_distribution: "uniform"

is_gpu: false

train_step_print: 10
valid_step_print: 100
save_step: 1000